// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHwt8ja4nj-gBO1ompLOMdpbK8eSxpTB4',
    appId: '1:1001460331009:web:a006e60c97c488b5ec8600',
    messagingSenderId: '1001460331009',
    projectId: 'quizapp-f559c',
    authDomain: 'quizapp-f559c.firebaseapp.com',
    storageBucket: 'quizapp-f559c.appspot.com',
    measurementId: 'G-Y3078DWKCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL1NxuV9TOO-fkXse4xiD0ppSSsQ3lKwc',
    appId: '1:1001460331009:android:89b1017c5d5b54f5ec8600',
    messagingSenderId: '1001460331009',
    projectId: 'quizapp-f559c',
    storageBucket: 'quizapp-f559c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK3LF0_OBb8Kez9j0ll_2oIBj4rfPLyY4',
    appId: '1:1001460331009:ios:0f6eba67a237e061ec8600',
    messagingSenderId: '1001460331009',
    projectId: 'quizapp-f559c',
    storageBucket: 'quizapp-f559c.appspot.com',
    androidClientId: '1001460331009-3sr9ae90hi776ip8f7j0h5vvced991dn.apps.googleusercontent.com',
    iosClientId: '1001460331009-uvgfhv1fs9mgo60s46ip2tsl3i5umq09.apps.googleusercontent.com',
    iosBundleId: 'io.ZiadAmr.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK3LF0_OBb8Kez9j0ll_2oIBj4rfPLyY4',
    appId: '1:1001460331009:ios:64f6326c1dc0d223ec8600',
    messagingSenderId: '1001460331009',
    projectId: 'quizapp-f559c',
    storageBucket: 'quizapp-f559c.appspot.com',
    androidClientId: '1001460331009-3sr9ae90hi776ip8f7j0h5vvced991dn.apps.googleusercontent.com',
    iosClientId: '1001460331009-sljmuuil8v2qts006a6ch5coji5ml7et.apps.googleusercontent.com',
    iosBundleId: 'io.ZiadAmr.quizapp.RunnerTests',
  );
}
